package ca.mcmaster.cas.se2aa4.a2.components;

/**
 * Vertex class which serves as a high-level recorder for the data generated by
 * the Generator and any properties from teh Mesh when finalized before
 * conversion.
 */
public class Vertex implements Vert {

    private int[] colour;

    private float thickness;

    private double x, y;

    private boolean centroid;

    public Vertex() {
        colour = new int[4];
        centroid = false;
    }

    public Vertex(double x, double y) {
        this();
        setPosition(x, y);
    }

    @Override
    public int compareTo(Vert v) {
        int comp = Double.compare(x, v.getX());
        return (comp != 0) ? comp : Double.compare(y, v.getY());
    }

    @Override
    public void setColour(int r, int g, int b, int a) {
        colour[0] = r;
        colour[1] = g;
        colour[2] = b;
        colour[3] = a;
    }

    @Override
    public void setThickness(float t) {
        thickness = t;
    }

    @Override
    public void setPosition(double x, double y) {
        this.x = x;
        this.y = y;
    }

    @Override
    public void setCentroid() {
        centroid = true;
    }

    @Override
    public int[] getColour() {
        return colour;
    }

    @Override
    public double getX() {
        return x;
    }

    @Override
    public double getY() {
        return y;
    }

    @Override
    public float getThickness() {
        return thickness;
    }

    @Override
    public boolean isCentroid() {
        return centroid;
    }

}
